### ISSUE TITLE
Excavate the logo (Remove Blocks Around)

### ISSUE THREAD

**Issue by 4val0v** [SimpleSoftwareIO/simple-qrcode#68]
Currently logos overlaid on top QR code :(
Will support excavate the logo ?

To the output we get this: http://imgur.com/a/XL2iO

**Comment by SimplyCorey** [comment]
@4val0v Hey there.  I think there is a language barrier as I do not understand your request.  Can you word it differently please?

**Comment by 4val0v** [comment]
At the moment, the picture is superimposed over QR code
Is it possible make the padding between the logo and the code?

http://imgur.com/a/bcQWp

**Comment by SimplyCorey** [comment]
It is not currently possible.  I will try to get this added in the next release.

**Comment by SimplyThomas** [comment]
@4val0v a workaround, for the moment, would be to add a margin to the image that is going to be added to the QrCode. So instead of your logo being cropped at the edge of the logo itself, it would have a transparent or white margin around it within the image file.

I don't see a benefit to adding this niche feature request in the code base when this workaround would solve the issue.
