### ISSUE TITLE
Logo on QR-Code

### ISSUE THREAD

**Issue by abstractFlo** [SimpleSoftwareIO/simple-qrcode#8]
Is there a way to implement a logo to the qrcode? I need this for my compay website :(

Kind regards

**Comment by SimplyCorey** [comment]
Currently, no but it is on our roadmap and I expect it to be out in 1-2 weeks after the Laravel 5 update.

If you need it sooner than that, I would suggest saving the qr code as a PNG and then adding the image on top of it.  Ensure you have high error correction so that the qr code is still able to scan.

**Comment by anil1712** [comment]
Hi, when you will add this feature? I am also waiting for this.

**Comment by SimplyCorey** [comment]
I will try to get this released this week.

I have been busy working on other projects, I apologize for the long delay.

**Comment by SimplyCorey** [comment]
After a long delay; I finished writing the code for this today.  I will release it this week once I finish up bug testing!
![sample](https://cloud.githubusercontent.com/assets/624784/8319843/90105424-19e1-11e5-9bfb-c09bbf4f6bd7.png)

**Comment by SimplyCorey** [comment]
Released in 1.3.0
