### ISSUE TITLE
After image merge qr not working 

### ISSUE THREAD

**Issue by rithikstan** [SimpleSoftwareIO/simple-qrcode#92]
after image merge, qr not working and image merge example qr also not working on this url https://www.simplesoftware.io/docs/simple-qrcode

**Comment by SimplyCorey** [comment]
I don't understand your request.  What is not working?

**Comment by rithikstan** [comment]
qr not working after merge image into qr

**Comment by rithikstan** [comment]
sir explain me the issue asap.

**Comment by SimplyCorey** [comment]
You need to bump the error correction to high.  Some Qr readers cant read the qrcode with an image.

**Comment by vaggelis2018** [comment]
@SimplyCorey I have the same issue. Qr works without the image but it losts data after image placement. If i decrease the image size, some data are shown but to make them all visible i have to make the image too small.

**Comment by SimplyCorey** [comment]
@vaggelis2018 That's the way this works.  The image placement relies on there being enough error correction for the reader to be able to pick up on the original code.  I suggest making the error correction large,  and having the image take up no more than 20-30% of the qrcode.  You will likely need to make the qrcode larger in order to have a large enough image.

**Comment by vaggelis2018** [comment]
Thanks for the quick response. I see it now and make it work. Thanks again.
